include: package:flutter_lints/flutter.yaml

linter:

  rules:
    always_declare_return_types: true
    require_trailing_commas: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**.g.dart"
    - "**/generated_plugin_registrant.dart"
